#pragma config(Sensor, S1,     sensor_color,   sensorEV3_Color, modeEV3Color_Color)
#pragma config(Motor,  motorA,          motor_left,    tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          motor_right,   tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#define TRUE 1
#define FALSE 0

#define NONE 0
#define BLACK 1
#define BLUE 2
#define GREEN 3
#define YELLOW 4
#define RED 5
#define WHITE 6
#define BROWN 7

#define ledOFF 0
#define ledGreen 1
#define ledRed 2
#define ledOrange 3
#define ledGreenFlash 4
#define ledRedFlash 5
#define ledOrangeFlash 6
#define ledGreenPulse 7
#define ledRedPulse 8
#define ledOrangePulse 9

/*
enum Syllable
{
   lowC = 523,
   lowCSharp = 554,
   lowD = 587,
   lowDSharp = 622,
   lowE = 659,
   lowF = 699,
   lowFSharp = 740,
   lowG = 784,
   lowGSharp = 831,
   lowA = 880,
   lowASharp = 932,
   lowB = 988,

   highC = 1047,
   highCSharp = 1109,
   highD = 1175,
   highDSharp = 1245,
   highE = 1319,
   highF = 1397,
   highFSharp = 1475,
   highG = 1568,
   highGSharp = 1661,
   highA = 1760,
   highASharp = 1865,
   highB = 1976
};
*/

void move(int speed)
{
   setMotorSpeed(motor_left, speed);
   setMotorSpeed(motor_right, speed);
}


task main()
{
   int start = FALSE;
   int speed = 20;

   while(TRUE)
   {
      if(getButtonPress(1))
      {
         move(speed);
         break;
      }
   }

   while(TRUE)
   {
      switch(getColorName(sensor_color))
      {
      case BLACK:
         displayBigTextLine(1, "BLACK");
         setLEDColor(ledGreen);
         sleep(50);
         /*
         if(!start)
         {
            setLEDColor(ledGreen);
            sleep(1000);
            start = TRUE;
         }
         else
         {
            move(0);
            sleep(1000);
            start = FALSE;
         }
         */
         break;
      case BLUE:
         displayBigTextLine(1, "BLUE");
         sleep(50);
         break;
      case GREEN:
         displayBigTextLine(1, "GREEN");
         playImmediateTone(523, 50);
         sleep(50);
         break;
      case YELLOW:
         displayBigTextLine(1, "YELLOW");
         move(speed/2);
         sleep(50);
         break;
      case RED:
         displayBigTextLine(1, "RED");
         move(0);
         sleep(1000);
         move(speed);
         sleep(50);
         break;
      case WHITE:
         displayBigTextLine(1, "WHITE");
         move(speed);
         sleep(50);
         break;
      }
   }
}
