//PID control

#pragma config(Sensor, S1,     sensorColorRight, sensorEV3_Color)
#pragma config(Sensor, S2,     sensorColorMiddle, sensorEV3_Color)
#pragma config(Sensor, S4,     sensorColorLeft, sensorEV3_Color)
#pragma config(Motor,  motorA,          motorLeft,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          motorRight,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
// 2.3 Two sensor boundary calculate


void move(int motorSpeedLeft, int motorSpeedRight, int period)
{
   setMotorSpeed(motorLeft, motorSpeedLeft);
   setMotorSpeed(motorRight, motorSpeedRight);
   sleep(period);
}



task main()
{
   int v = 35;
   int error = 0;
   int sum = 0;
   int diff = 0;
   int last_error = 0;
   int threshold = 38;

   float Kp = 0.05;
   float Kd = 10;
   float Ki = Kp * Kp/(4*Kd);

   // Before starting..
   while(TRUE)
   {
      if(getButtonPress(TRUE))
      {
         break;
      }
   }

   while(TRUE)
   {
      error = getColorReflected(sensorColorMiddle) - threshold; // P control
      sum += error; // PI control
      diff = error - last_error; // PID control
      move(v+(error*Kp + sum*Ki + diff*Kd), v-(error*Kp + sum*Ki + diff*Kd), 1);
      last_error = error;
   }
}
