#pragma config(Sensor, S1,     c3,             sensorEV3_Color)
#pragma config(Sensor, S2,     c2,             sensorEV3_Color)
#pragma config(Sensor, S4,     c1,             sensorEV3_Color)
#pragma config(Motor,  motorA,          lm,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          rm,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define DIFF 10

int nMotorSpeedSetting = 28;
float P = 0.3, I = 0.00001, D = 100, e = 0.0, s = 0.0, pre = 0;
int gray[3], dark[3], bright[3], TURN[3], cnt = 0, gcnt = 0;
bool turnFlag = false, L = false, R = false, B =false, Gflag = false;
int stack[10] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
int index = 0;
bool reFlag = false;

void scanLine()
{
   displayBigTextLine(1, "scan dark area!!");
   displayBigTextLine(4, "& push up button!!");
   while(getButtonPress(1)==0)sleep(10); playTone(440,20);
   dark[0] = getColorReflected(c1);
   dark[1] = getColorReflected(c2);
   dark[2] = getColorReflected(c3);
   sleep(1000);
   displayBigTextLine(1, "scan bright area!!");
   displayBigTextLine(4, "& push up button!!");
   while(getButtonPress(1)==0)sleep(10); playTone(440,20);
   bright[0] = getColorReflected(c1);
   bright[1] = getColorReflected(c2);
   bright[2] = getColorReflected(c3);
   sleep(1000);
   displayBigTextLine(1, "%d %d %d", bright[0], bright[1], bright[2]);
   displayBigTextLine(4, "%d %d %d", dark[0], dark[1], dark[2]);
  for(int i = 0; i<3; i++)
  {
     gray[i] = (dark[i] + bright[i])/2;
  }
  displayBigTextLine(7, "%d %d %d", gray[0], gray[1], gray[2]);
   displayBigTextLine(10, "push up to Start!");
}

void go()
{
   pre = e; e = getColorReflected(c2)-gray[1]; s += e; pre = e -pre;
   setMotorSpeed(lm, nMotorSpeedSetting + round(e*P + s*I + pre*D));
   setMotorSpeed(rm, nMotorSpeedSetting - round(e*P + s*I + pre*D));
}

void isCross()
{
   if(getColorReflected(c1) < gray[0] || getColorReflected(c3)<gray[2])
   {
      setMotorSpeed(lm, 20);
      setMotorSpeed(rm, 20);
      sleep(160);
      if(getColorReflected(c1) < gray[0])
      {
         L = true;
      }
      else if(L==true)
      {
         turnFlag = true;
         TURN[0] = 1;
      }

      if(getColorReflected(c3) <gray[2])
      {
         R = true;
      }
      else if(R == true)
      {
         turnFlag = true;
         TURN[1] = 1;
      }
      if(getColorReflected(c1) <=gray[0] && getColorReflected(c3) <=gray[2] && getColorReflected(c2) <=gray[1])
      {
         gcnt++;
      }
      else gcnt =0;

      if(gcnt>5) Gflag =true;
   }

   if(getColorReflected(c2)>gray[1]*8/5)
   {
      cnt++;
   }
   else
   {
      cnt = 0;
   }

   if(cnt>500)
   {
      B = true;
      turnFlag = true;
      TURN[2] = 1;
   }
}

void turnLeft()
{
   eraseDisplay();
   if(L==true)displayBigTextLine(11, "TurnLeft!");
   while(getColorReflected(c1) > gray[0])
   {
      setMotorSpeed(lm, -nMotorSpeedSetting*6/10);
      setMotorSpeed(rm, nMotorSpeedSetting*6/10);
   }
   while(getColorReflected(c2) > gray[1])
   {
      setMotorSpeed(lm, -nMotorSpeedSetting*6/10);
      setMotorSpeed(rm, nMotorSpeedSetting*6/10);
   }
   while(getColorReflected(c2) <= gray[1])
   {
      setMotorSpeed(lm, -nMotorSpeedSetting*6/10);
      setMotorSpeed(rm, nMotorSpeedSetting*6/10);
   }
   setMotorSpeed(lm,0);
   setMotorSpeed(rm,0);

   if(!reFlag)
   {
      index += 1;
      stack[index] += 1;
   }

}

void turnRight()
{
    if(R==true)displayBigTextLine(11, "TurnRight!");
   while(getColorReflected(c2) <= gray[1])
   {
      setMotorSpeed(lm, nMotorSpeedSetting);
      setMotorSpeed(rm, -nMotorSpeedSetting);
   }
   while(getColorReflected(c2) > gray[1])
   {
      setMotorSpeed(lm, nMotorSpeedSetting);
      setMotorSpeed(rm, -nMotorSpeedSetting);
   }

   setMotorSpeed(lm,0);
   setMotorSpeed(rm,0);

   if(!reFlag)
   {
      index += 1;
      stack[index] += 3;
   }
}

void stopMotor()
{
   eraseDisplay();
   setMotorSpeed(lm, 0);
   setMotorSpeed(rm, 0);
   //if(L == true) displayBigTextLine(1, "Left");
   //if(R == true) displayBigTextLine(4, "Right");
   //if(B == true) displayBigTextLine(7, "Back");
}

void statusReset()
{
   turnFlag = L = R = B = Gflag = false;
   cnt = gcnt = TURN[0] = TURN[1] = TURN[2] = 0;
}

task main()
{
   scanLine();
   while(getButtonPress(1) == 0) sleep(10);
   setMotorSpeed(lm, nMotorSpeedSetting);
   setMotorSpeed(rm, nMotorSpeedSetting);
   sleep(1000);
   eraseDisplay();

   while(true)
   {
      go();
      isCross();
      if(turnFlag)
      {
         setMotorSpeed(lm, 20);
         setMotorSpeed(rm, 20);
         sleep(500);
         stopMotor();
         if(TURN[0] == 1)
         {
           turnLeft();
         }
         else if(TURN[2] == 1) //U turn
         {
            displayBigTextLine(3, "U-turn");
            setMotorSpeed(lm, -30);
            setMotorSpeed(rm, -11);
            sleep(600);
            turnLeft();
            stack[index] += 3;
            if(stack[index] == 4)
            {
               stack[index] = 0;
               index -= 2;
            }
         }
         else if(TURN[1] == 1 && getColorReflected(c2) > gray[1]) // right
         {
            turnRight();
         }
             else // staright
             {
               if(!reflag)
               {
                 displayBigTextLine(11, "straight");
                 index += 2;
                   stack[index] += 1;
               }
             }
         statusReset();
         // displayBigTextLine(3, "idx: %d", index);
          // displayBigTextLine(6, "s[idx]: %d", stack[index]);
      }

      if(Gflag)
      {
         statusReset();
         break;
      }

      if(stack[index] == 4)
      {
         stack[index] = 0;
         index -= 2;
      }

   }

   reFlag = true;
   // finish
   playTone(240, 20); sleep(200);
   stopMotor();

   displayBigTextLine(3, "%d%d%d%d%d%d%d%d", stack[0], stack[1], stack[2], stack[3], stack[4], stack[5], stack[6], stack[7]);

   // back
   setMotorSpeed(lm, -30);
     setMotorSpeed(rm, -30);
    sleep(1000);

   // U-tern
     setMotorSpeed(lm, -30);
     setMotorSpeed(rm, -11);
    sleep(600);
    turnLeft();
    stopMotor();

   // restart
   while(true)
   {
      go();
      isCross();

      if(turnFlag)
      {
            setMotorSpeed(lm, 20);
            setMotorSpeed(rm, 20);
            sleep(500);
            stopMotor();

            if(stack[index] == 3)
            {
               turnLeft();
            }
            else if(stack[index] == 1)
            {
               turnRight();
            }
            else if(stack[index] == 2)// straight
            {
               setMotorSpeed(lm, 20);
               setMotorSpeed(rm, 20);
               sleep(500);
               stopMotor();
            }
            statusReset();
            index--;
      }
   }

}
