#pragma config(Sensor, S1, sensorR, sensorEV3_Color)
#pragma config(Sensor, S2, sensorM, sensorEV3_Color)
#pragma config(Sensor, S4, sensorL, sensorEV3_Color)
#pragma config(Motor, motorA, motorLeft, tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor, motorD, motorRight, tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define TRUE 1
#define FALSE 0

#define LOW_C 523
#define LOW_C_SHARP 554
#define LOW_D 587
#define LOW_D_SHARP 622
#define LOW_E 659
#define LOW_F 699
#define LOW_F_SHARP 740
#define LOW_G 784
#define LOW_G_SHARP 831
#define LOW_A 880
#define LOW_A_SHARP 932
#define LOW_B 988
#define HIGH_C 1047
#define HIGH_C_SHARP 1109
#define HIGH_D 1175
#define HIGH_D_SHARP 1245
#define HIGH_E 1319
#define HIGH_F 1397
#define HIGH_F_SHARP 1475
#define HIGH_G 1568
#define HIGH_G_SHARP 1661
#define HIGH_A 1760
#define HIGH_A_SHARP 1865
#define HIGH_B 1976

#define MSEC_0_05 50
#define MSEC_0_10 100
#define MSEC_0_50 500
#define MSEC_1_00 1000


void turnleft()
{
		setMotorSpeed(motorLeft, -10);
  	setMotorSpeed(motorRight, 10);
  	//sleep(3);
}


task main()
{
    turnleft();
    sleep(1450);
    setMotorSpeed(motorLeft, 0);
  	setMotorSpeed(motorRight, 0);
  	sleep(1450);
    setMotorSpeed(motorLeft, 10);
  	setMotorSpeed(motorRight, 10);
  	sleep(1450);

}
