#pragma config(Sensor, S1,     color,          sensorEV3_Color, modeEV3Color_Color)
#pragma config(Motor,  motorA,          motor_a,       tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          motor_d,       tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define BLACK 1
#define GREEN 3
#define RED 5
#define YELLOW 4
int speed = 20;
//error
void Go(){
	setMotorSpeed(motor_a, speed);
	setMotorSpeed(motor_d, speed);
}

void Go_slow(){
	setMotorSpeed(motor_a, speed/2);
	setMotorSpeed(motor_d, speed/2);
}

task main()
{

	int sound[1] = {523};
	int val=0;
	//int song[100] = {}

	while(1){

		if(getButtonPress(1)){
			Go();

			if(getColorName(color) == BLACK){
				displayBigTextLine(1, "Color : %d ",getColorName(color));
				sleep(500);
				Go();
				setLEDColor(1);
			}
			else if(getColorName(color) == GREEN){
				displayBigTextLine(1, "Color : %d ",getColorName(color));
				sleep(500);
				val++;
				Go();
				playImmediateTone(sound[0], 50);
				//sleep(1000);
			}
			else if(getColorName(color) == YELLOW){
				displayBigTextLine(1, "Color : %d ",getColorName(color));
				sleep(500);
				val++;
				Go_slow();
				setMotorSpeed(motor_a, speed/2);
				setMotorSpeed(motor_d, speed/2);
			}
			else if(getColorName(color) == RED){
				displayBigTextLine(1, "Color : %d ",getColorName(color));
				sleep(500);
				val++;
				Go();
				sleep(1000);
			}
			else if((val > 0) && (getColorName(color) == BLACK)){
				displayBigTextLine(1, "Color : %d ",getColorName(color));
				sleep(500);
				setMotorSpeed(motor_a, 0);
				setMotorSpeed(motor_d, 0);
				break;
			}
		}
	}

