#pragma config(Sensor, S1,     sensor_color,   sensorEV3_Color, modeEV3Color_Color)
#pragma config(Motor,  motorA,          motor_left,    tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          motor_right,   tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#define TRUE 1
#define FALSE 0

#define NONE 0
#define BLACK 1
#define BLUE 2
#define GREEN 3
#define YELLOW 4
#define RED 5
#define WHITE 6
#define BROWN 7

#define ledOFF 0
#define ledGreen 1
#define ledRed 2
#define ledOrange 3
#define ledGreenFlash 4
#define ledRedFlash 5
#define ledOrangeFlash 6
#define ledGreenPulse 7
#define ledRedPulse 8
#define ledOrangePulse 9

enum Syllable
{
	lowC = 523,
	lowCSharp = 554,
	lowD = 587,
	lowDSharp = 622,
	lowE = 659,
	lowF = 699,
	lowFSharp = 740,
	lowG = 784,
	lowGSharp = 831,
	lowA = 880,
	lowASharp = 932,
	lowB = 988,

	highC = 1047,
	highCSharp = 1109,
	highD = 1175,
	highDSharp = 1245,
	highE = 1319,
	highF = 1397,
	highFSharp = 1475,
	highG = 1568,
	highGSharp = 1661,
	highA = 1760,
	highASharp = 1865,
	highB = 1976
};

void move(int speed)
{

}


task main()
{
	while(TRUE)
	{
		if(getButtonPress(1))
		{
			setMotorSpeed(motor_left, 30);
			setMotorSpeed(motor_right, 30);
		}

		switch(getColorName(sensor_color))
		{
		case BLACK:
			displayBigTextLine(1, "BLACK");
			setLEDColor(ledGreen);
			sleep(500);
			break;
		/*
		case BLUE:
			displayBigTextLine(1, "BLUE");
			sleep(500);
			break;
		case GREEN:
			displayBigTextLine(1, "GREEN");
			sleep(500);
			break;
		case RED:
			displayBigTextLine(1, "RED");
			sleep(500);
			break;
		case YELLOW:
			displayBigTextLine(1, "YELLOW");
			sleep(500);
			break;
		*/
		}

		switch(getColorName(sensor_color))
		{
		case BLACK:
			displayBigTextLine(1, "BLACK");
			setLEDColor(ledGreen);
			sleep(500);
			break;
		case BLUE:
			displayBigTextLine(1, "BLUE");
			sleep(500);
			break;
		case GREEN:
			displayBigTextLine(1, "GREEN");
			playImmediateTone(523, 50);
			sleep(500);
			break;
		case RED:
			displayBigTextLine(1, "RED");
			sleep(500);
			break;
		case YELLOW:
			displayBigTextLine(1, "YELLOW");
			sleep(500);
			break;
		}

		switch(getColorName(sensor_color))
		{
		case BLACK:
			displayBigTextLine(1, "BLACK");
			setLEDColor(ledGreen);
			sleep(500);
			break;
		case BLUE:
			displayBigTextLine(1, "BLUE");
			sleep(500);
			break;
		case GREEN:
			displayBigTextLine(1, "GREEN");
			playImmediateTone(523, 50);
			sleep(500);
			break;
		case RED:
			displayBigTextLine(1, "RED");
			sleep(500);
			break;
		case YELLOW:
			displayBigTextLine(1, "YELLOW");
			setMotorSpeed(motor_left, 10);
			setMotorSpeed(motor_right, 10);
			sleep(500);
			break;
		}

		switch(getColorName(sensor_color))
		{
		case BLACK:
			displayBigTextLine(1, "BLACK");
			setLEDColor(ledGreen);
			sleep(500);
			break;
		case BLUE:
			displayBigTextLine(1, "BLUE");
			sleep(500);
			break;
		case GREEN:
			displayBigTextLine(1, "GREEN");
			playImmediateTone(523, 50);
			sleep(500);
			break;
		case RED:
			displayBigTextLine(1, "RED");
			sleep(500);
			break;
		case YELLOW:
			displayBigTextLine(1, "YELLOW");
			sleep(500);
			break;
		case WHITE:
			displayBigTextLine(1, "WHITE");
			setMotorSpeed(motor_left, 30);
			setMotorSpeed(motor_right, 30);
			sleep(500);
			break;
		}

		switch(getColorName(sensor_color))
		{
		case BLACK:
			displayBigTextLine(1, "BLACK");
			setLEDColor(ledGreen);
			sleep(500);
			break;
		case BLUE:
			displayBigTextLine(1, "BLUE");
			sleep(500);
			break;
		case GREEN:
			displayBigTextLine(1, "GREEN");
			playImmediateTone(523, 50);
			sleep(500);
			break;
		case RED:
			displayBigTextLine(1, "RED");
			setMotorSpeed(motor_left, 0);
			setMotorSpeed(motor_right, 0);
			sleep(1000);
			setMotorSpeed(motor_left, 30);
			setMotorSpeed(motor_right, 30);
			break;
		case YELLOW:
			displayBigTextLine(1, "YELLOW");
			sleep(500);
			break;
		case WHITE:
			displayBigTextLine(1, "WHITE");
			sleep(500);
			break;
		}
		/*
		if(getButtonPress(1))
		{
			move(30);
			if(getColorName(sensor_color) == BLACK)
			{
				setLEDColor(ledRed);

				sleep(1000);
			}
		}
		*/
	}
}
